language: ruby
sudo: false
cache: bundler
script: "bundle exec rake"
# Source: <https://docs.travis-ci.com/user/languages/ruby/#bundler-20>
before_install:
  - gem update --system '2.7.8' --no-document
  - bundle --version
  - gem uninstall bundler -ax
  - gem install bundler -v '< 2' --no-document
  - bundle --version
install: "bundle install --jobs=3 --retry=3"

env:
  - DATABASE_ADAPTER=sqlite3
  - DATABASE_ADAPTER=postgresql

rvm:
  - 2.6.2
  - 2.5.4
  - 2.4.4
  - 2.3.7

gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile

matrix:
  exclude:
    - rvm: 2.6.2
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/rails_6_0.gemfile
